version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - whoiswho:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  node-app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}

volumes:
  whoiswho: