version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - whoiswho:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  node-app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}

  react-app:
    build: ../frontend/
    depends_on:
      - node-app
    ports:
      - "3000:80"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pedro@email.com
      PGADMIN_DEFAULT_PASSWORD: senha123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    restart: unless-stopped

volumes:
  whoiswho: